### ISSUE TITLE
Error adding package

### ISSUE THREAD

**Issue by weholt** [pydanny/djangopackages#423] opened 2017-01-24 15:19 UTC
I tried to add my package by entering a link to my github repo at https://github.com/weholt/massiviu, but got an error saying:

"Error

If this seems like a bug, would you please do us a favor and create a ticket?"

So yeah - I'd like to add a ticket. Would be nice with a bit more info in the error message at least.

**Comment by pydanny** [comment] 2017-01-24 15:45
Duplicate of #373

**Closed by pydanny** 2017-01-24 15:45 UTC
Labels: Duplicate
