### ISSUE TITLE
API v3 Server 500 Errors

### ISSUE THREAD

**Issue by grantjenks** [pydanny/djangopackages#351] opened 2016-10-29 21:17 UTC
Duplicate of #350. I don't have permission to reopen.

```
In [10]: for offset in offsets:
    resp = requests.get(url + offset)
    print url + offset, resp.status_code
   ....:     
https://djangopackages.org/api/v3/packages/?limit=20&offset=1000 500
https://djangopackages.org/api/v3/packages/?limit=20&offset=1620 500
https://djangopackages.org/api/v3/packages/?limit=20&offset=1700 500
https://djangopackages.org/api/v3/packages/?limit=20&offset=2340 500
https://djangopackages.org/api/v3/packages/?limit=20&offset=2400 500

In [11]: print offsets
['1000', '1620', '1700', '2340', '2400']
```

Just tested and these offsets fail with 500 Server Error.

Here's my test code:

```
In [3]: url = 'https://djangopackages.org/api/v3/packages/?limit=20&offset='

In [4]: for offset in range(0, 4000, 20):
   ...:     resp = requests.get(url + str(offset))
   ...:     print offset, resp
```

**Comment by michaeljohnbarr** [comment] 2016-11-01 03:28
Confirmed issue. Here's the full result set from my test run.
```
0 <Response [200]>
20 <Response [200]>
40 <Response [200]>
60 <Response [200]>
80 <Response [200]>
100 <Response [200]>
120 <Response [200]>
140 <Response [200]>
160 <Response [200]>
180 <Response [200]>
200 <Response [200]>
220 <Response [200]>
240 <Response [200]>
260 <Response [200]>
280 <Response [200]>
300 <Response [200]>
320 <Response [200]>
340 <Response [200]>
360 <Response [200]>
380 <Response [200]>
400 <Response [200]>
420 <Response [200]>
440 <Response [200]>
460 <Response [200]>
480 <Response [200]>
500 <Response [200]>
520 <Response [200]>
540 <Response [200]>
560 <Response [200]>
580 <Response [200]>
600 <Response [200]>
620 <Response [200]>
640 <Response [200]>
660 <Response [200]>
680 <Response [200]>
700 <Response [200]>
720 <Response [200]>
740 <Response [200]>
760 <Response [200]>
780 <Response [200]>
800 <Response [200]>
820 <Response [200]>
840 <Response [200]>
860 <Response [200]>
880 <Response [200]>
900 <Response [200]>
920 <Response [200]>
940 <Response [200]>
960 <Response [200]>
980 <Response [200]>
1000 <Response [500]>
1020 <Response [200]>
1040 <Response [200]>
1060 <Response [200]>
1080 <Response [200]>
1100 <Response [200]>
1120 <Response [200]>
1140 <Response [200]>
1160 <Response [200]>
1180 <Response [200]>
1200 <Response [200]>
1220 <Response [200]>
1240 <Response [200]>
1260 <Response [200]>
1280 <Response [200]>
1300 <Response [200]>
1320 <Response [200]>
1340 <Response [200]>
1360 <Response [200]>
1380 <Response [200]>
1400 <Response [200]>
1420 <Response [200]>
1440 <Response [200]>
1460 <Response [200]>
1480 <Response [200]>
1500 <Response [200]>
1520 <Response [200]>
1540 <Response [200]>
1560 <Response [200]>
1580 <Response [200]>
1600 <Response [200]>
1620 <Response [500]>
1640 <Response [200]>
1660 <Response [200]>
1680 <Response [200]>
1700 <Response [500]>
1720 <Response [200]>
1740 <Response [200]>
1760 <Response [200]>
1780 <Response [200]>
1800 <Response [200]>
1820 <Response [200]>
1840 <Response [200]>
1860 <Response [200]>
1880 <Response [200]>
1900 <Response [200]>
1920 <Response [200]>
1940 <Response [200]>
1960 <Response [200]>
1980 <Response [200]>
2000 <Response [200]>
2020 <Response [200]>
2040 <Response [200]>
2060 <Response [200]>
2080 <Response [200]>
2100 <Response [200]>
2120 <Response [200]>
2140 <Response [200]>
2160 <Response [200]>
2180 <Response [200]>
2200 <Response [200]>
2220 <Response [200]>
2240 <Response [200]>
2260 <Response [200]>
2280 <Response [200]>
2300 <Response [200]>
2320 <Response [200]>
2340 <Response [500]>
2360 <Response [200]>
2380 <Response [200]>
2400 <Response [500]>
2420 <Response [200]>
2440 <Response [200]>
2460 <Response [200]>
2480 <Response [200]>
2500 <Response [200]>
2520 <Response [200]>
2540 <Response [200]>
2560 <Response [200]>
2580 <Response [200]>
2600 <Response [200]>
2620 <Response [200]>
2640 <Response [200]>
2660 <Response [200]>
2680 <Response [200]>
2700 <Response [200]>
2720 <Response [200]>
2740 <Response [200]>
2760 <Response [200]>
2780 <Response [200]>
2800 <Response [200]>
2820 <Response [200]>
2840 <Response [200]>
2860 <Response [200]>
2880 <Response [200]>
2900 <Response [200]>
2920 <Response [200]>
2940 <Response [200]>
2960 <Response [200]>
2980 <Response [200]>
3000 <Response [200]>
3020 <Response [200]>
3040 <Response [200]>
3060 <Response [200]>
3080 <Response [200]>
3100 <Response [200]>
3120 <Response [200]>
3140 <Response [200]>
3160 <Response [200]>
3180 <Response [200]>
3200 <Response [200]>
3220 <Response [200]>
3240 <Response [200]>
3260 <Response [200]>
3280 <Response [200]>
3300 <Response [200]>
3320 <Response [200]>
3340 <Response [200]>
3360 <Response [200]>
3380 <Response [200]>
3400 <Response [200]>
3420 <Response [200]>
3440 <Response [200]>
3460 <Response [200]>
3480 <Response [200]>
3500 <Response [200]>
3520 <Response [200]>
3540 <Response [200]>
3560 <Response [200]>
3580 <Response [200]>
3600 <Response [200]>
3620 <Response [200]>
3640 <Response [200]>
3660 <Response [200]>
3680 <Response [200]>
3700 <Response [200]>
3720 <Response [200]>
3740 <Response [200]>
3760 <Response [200]>
3780 <Response [200]>
3800 <Response [200]>
3820 <Response [200]>
3840 <Response [200]>
3860 <Response [200]>
3880 <Response [200]>
3900 <Response [200]>
3920 <Response [200]>
3940 <Response [200]>
3960 <Response [200]>
3980 <Response [200]>
```

Process finished with exit code 0

**Comment by michaeljohnbarr** [comment] 2016-11-01 03:56
@pydanny - further research https://djangopackages.org/api/v3/packages/?limit=20&offset=990 causes a 500 error, but https://djangopackages.org/api/v3/packages/?limit=20&offset=889 does not. So to narrow the issue down, we need to find the package which is causing the error to occur.

The last title (that's what I see that the ordering defaults to) is "Django Fixture Tools." So the one after that appears to be causing the issue.

**Comment by michaeljohnbarr** [comment] 2016-11-01 04:03
I believe the issue is with django-flag: https://djangopackages.org/api/v3/packages/django-flag/

**Comment by pydanny** [comment] 2016-11-02 17:17
Wahoo! Just replicated the issue! I'll start working on it.

**Comment by jayfk** [comment] 2017-04-11 14:01
Fixed in https://github.com/pydanny/djangopackages/commit/744095c23181140259d65d935bc8932363a6cec9

**Closed by jayfk** 2017-04-11 14:01 UTC
