### ISSUE TITLE
Failed to add new django packages / add

### ISSUE THREAD

**Issue by ismailsunni** [pydanny/djangopackages#420] opened 2017-01-24 03:22 UTC
I was trying to register my django app, https://github.com/kartoza/geonode_qgis_server, but I got this error page:
<img width="1425" alt="screen shot 2017-01-24 at 10 21 29" src="https://cloud.githubusercontent.com/assets/1421861/22232904/f0b48c8a-e21e-11e6-9414-2dc18663fd56.png">

**Comment by pydanny** [comment] 2017-01-24 06:16
Duplicate of #373

**Closed by pydanny** 2017-01-24 06:16 UTC
Labels: Duplicate
